HomeWork sql(26-32)
DadizhaO/MateAcademy pull request #13
Opened 2019-02-07 10:03 UTC by DadizhaO

2019-02-07 11:28 UTC, SerhiiPasko requested changes
Where is my task?

2019-02-07 11:28 UTC, SergeyPasko commented on src/main/resources/sql/QuarryHM.sql
> +    JOIN customers   cus ON ord.cust = cus.cust_num;
write inner join - it is more readable

2019-02-07 13:42 UTC, SerhiiPasko approved these changes
Read comment

2019-02-07 13:42 UTC, SergeyPasko commented on src/main/resources/sql/QuarryHM.sql
> +SELECT * FROM customers cus
You have there many times repeats company names

2019-02-09 22:01 UTC, Taniann approved these changes

2019-02-11 16:19 UTC, merged